FROM n8nio/runners:2.10.0

USER root
RUN cd /opt/runners/task-runner-python && uv pip install pandas numpy requests beautifulsoup4 lxml openpyxl
COPY n8n-task-runners.json /etc/n8n-task-runners.json
USER runner
